### ISSUE TITLE
TypeError: Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by lagats** [kadamwhite/block-editor-hmr#6]
Hi, i followed your readme in an attept to get this working with my project, however once i make a change to my block content i get this error, i was hoping you have some suggestions on how to remedy this.

`TypeError: Cannot read property 'title' of undefined
    at block_BlockListBlock (http://localhost/wp/nba-csiroscope/wp-includes/js/dist/block-editor.js?ver=aacb5c07c68e448af6536df79db8f400:16200:123)
    at block_BlockListBlock (http://localhost:3030/dist//js/block.js?ver=5.4.1:6466:20)
    at renderWithHooks (http://localhost/wp/nba-csiroscope/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:15246:18)
    at updateFunctionComponent (http://localhost/wp/nba-csiroscope/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:17063:20)
    at beginWork$1 (http://localhost/wp/nba-csiroscope/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:18636:16)
    at HTMLUnknownElement.callCallback (http://localhost/wp/nba-csiroscope/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:341:14)
    at Object.invokeGuardedCallbackDev (http://localhost/wp/nba-csiroscope/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:391:16)
    at invokeGuardedCallback (http://localhost/wp/nba-csiroscope/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:448:31)
    at beginWork$$1 (http://localhost/wp/nba-csiroscope/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:23355:7)
    at performUnitOfWork (http://localhost/wp/nba-csiroscope/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:22346:12)`

**Comment by lmartins** [comment]
@lagats running into the same issue, did you find a way around it?
I think something changed in WordPress that breaks Webpack's HMR functionality, but not quite able to figure it out. Would be great if @kadamwhite could chime in.

**Comment by lmartins** [comment]
Any help here would be much appreciated. When I get `webpack dev-server` running, it gets connected to the browser correctly: https://cln.sh/KsHWcL

But then as soon as I make a edit to a block that is being used on the page:
https://cln.sh/LlcMDk
https://cln.sh/Hn7Wsb

Based on this last screenshot it appears that as far as Webpack goes it is doing the HMR, but the editor is crashing as it tries to read the property "title" from this minified `J` object which I assume is a block object:
https://cln.sh/FzDxtN

Have any of you been able to get past this?

**Comment by lmartins** [comment]
@kadamwhite with all due respect, and please know that I understand how much of burden this may be, but if the Issues section on these repos are going to be pretty much ignored, why not just close them? 

I think it would set better expectations for users, who at that point would know not to expect any feedback or support here.

I'm not saying this based on this ticket alone. I've commented on other repos where too there was zero feedback, which again totally your right to do so, but in which case would be best for everyone if you just dropped the issues section altogether.  Thank you.

**Comment by leeshadle** [comment]
Hi @lmartins,
I ran into this issue as well and it seemed to resolve with the latest version of the gutenberg plugin and the latest release of WordPress.  Are you using the Gutenberg plugin for development?  Also, what version of WordPress are you on?

**Comment by lmartins** [comment]
@leeshadle oh that is great news. I'm on WordPress 5.4.2 but not using the standalone Gutenberg plugin as I'm trying to stick closer to the production environment. But what you say does confirm for me too, that is great news, I'll setup a test environment to see if it behaves the same for me. Thank you for chiming in Lee.

**Comment by lmartins** [comment]
@leeshadle you're right, using the plugin the error doesn't happen when refreshing live-reloading blocks. Super interesting. Not really sure why that is, but at least this allows me to continue to use the tool. Thanks so much for the suggestion man 🙌

**Comment by kadamwhite** [comment]
I'm trying to reproduce this on WP 5.4.2 and it is working as expected in a local virtual machine. Can one of you provide a reduced test case of a block definition where you're encountering this problem?

**Comment by kadamwhite** [comment]
@lmartins @leeshadle Other information I could use to reproduce this issue:

- What type of edit causes the error

- Webpack version
- Webpack DevServer version
- Node version
- WordPress version, if not 5.4.2, or version of the Gutenberg plugin, if applicable

**Comment by kadamwhite** [comment]
Apologies, I have now reproduced it after disabling an unrelated customization in the 5.4.2 environment. Investigating a workaround for that version now, though I have also validated that WP 5.5 alpha seems to work as expected.

**Comment by kadamwhite** [comment]
I've pushed a new branch with a provisional fix. If you pull that version down and build it, the module will then export a `_apply_wp_5_4_hmr_patch` method which you can import and call from your plugin entrypoint.

We'll continue to investigate whether there's a more robust workaround... perhaps something around wrapping the BlockListBlock in a block which is itself store-connected, which can then opt out of rendering.

**Comment by kadamwhite** [comment]
This fix has shipped in 0.6.1, so updating your package should now enable you to opt-in to the workaround. I released it as a patch instead of a point release so that the change is quickly available where it's needed, but I do hope to find a more robust workaround for this later.
